config/routes.rb
Briandmcnabb::Application.routes.draw do

  # Backend Administrative Interface
  constraints subdomain: "admin" do
    scope module: "admin", as: "admin"  do
      resources :services do
        collection { post :sort }
        resources :skills
      end
      resources :clients do
        collection { post :sort }
        resources :projects
      end
      resources :inquiries
      resources :posts do
        collection { post :sort }
      end
      match '/auth/:provider/callback' => 'omniauth#callback'
      match '/auth/failure' => 'omniauth#failure'
      resources :connections, only: [:index, :create, :destroy]
      resource :user
      root to: "posts#index"
    end
  end

  devise_for :user,     skip: :registrations
  resource   :user,     only: :show,           path: "/about"
  resources  :clients,  only: :index,          path: "/work"
  resources  :posts,    only: [:index, :show], path: "/blog/posts"
  resources  :services, only: [:index, :show]

  # Dynamic Root Route
  root to: "users#show"
  
end

app/models/client.rb
# == Schema Information
#
# Table name: clients
#
#  id           :integer         not null, primary key
#  position     :integer
#  organization :string(255)
#  first_name   :string(255)
#  last_name    :string(255)
#  email        :string(255)
#  url          :string(255)
#  description  :text
#  created_at   :datetime
#  updated_at   :datetime
#

class Client < ActiveRecord::Base
  acts_as_list
  
  # Accessors
  attr_accessible :position, :organization, :first_name, :last_name, :email, :url, :description, :client_logo_attributes, :service_tokens
  attr_reader :service_tokens
  
  def service_tokens=(ids)
    self.service_ids = ids.split(",")
  end


  # Associations
  has_one :client_logo, :as => :attachable, :dependent => :destroy
  has_many :projects, :dependent => :destroy
  has_many :images, :through => :projects
  has_and_belongs_to_many :services


  # Nested Models
  accepts_nested_attributes_for :client_logo, :reject_if => :all_blank, :allow_destroy => true
  
  
  # Scopes
  default_scope order: 'position'


  # Methods
  def to_s
    self.organization
  end
end

app/controllers/admin/clients_controller.rb
class Admin::ClientsController < Admin::ResourceController
  def sort
    params[:client].each_with_index do |id, index|
      Client.update_all({position: index+1}, {id: id})
    end
    render nothing: true
  end
end

app/controllers/clients_controller.rb
class ClientsController < ResourceController
  protected
    def collection
      @clients ||= end_of_association_chain.includes(:client_logo, :projects, :images, :services)
    end
end

app/views/admin/clients/_client_logo_fields.html.haml
.clearfix
	= image_tag(f.object.asset_path_url(:thumb)) if f.object.asset_path?
	= f.input :asset_path, :label => false
	= f.input :asset_path_cache, :as => :hidden
	- unless resource.new_record?
		= f.input :remove_asset_path, :label => "remove", :as => :boolean

app/views/admin/clients/_form.html.haml
= simple_nested_form_for [ :admin, resource ], html: { multipart: true} do |f|
	.clearfix	
		%fieldset#left_column
			%legend Client
			= f.input :organization
			= f.input :first_name
			= f.input :last_name
			= f.input :email
			= f.input :url
			= f.input :description
			= f.input :service_tokens, label: 'Services', input_html:{ data:{ source: Service.order(:name).map(&:name) } }
		%fieldset#right_column
			%legend Logo
			= f.simple_fields_for :client_logo
			= f.link_to_add( "add logo", :client_logo) unless resource.client_logo
	= f.button :submit, "submit"
	
- content_for :head do
	= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css"

app/views/admin/clients/_image_fields.html.haml
= #image_tag(resource.avatar.asset_path_url(:thumb)) if resource.avatar && resource.avatar.asset_path?
= f.input :asset_path, :label => false
= f.input :asset_path_cache, :as => :hidden
- unless resource.new_record?
	= f.input :remove_asset_path, :label => "remove", :as => :boolean
= f.link_to_remove "remove", :class => 'one_liner'

app/views/admin/clients/index.html.haml
= render "index", attributes: %w(organization first_name last_name email url)

app/views/admin/clients/show.html.haml
= render "show", attributes: attributes
#projects
	%h1 Projects
	%ul
		%li= link_to "Add a new project", new_admin_client_project_path(resource.id)
		- resource.projects.each do |project|
			%li= link_to project.title, admin_client_project_path(resource, project)
		