config/routes.rb
Briandmcnabb::Application.routes.draw do

  # Backend Administrative Interface
  constraints subdomain: "admin" do
    scope module: "admin", as: "admin"  do
      resources :services do
        collection { post :sort }
        resources :skills
      end
      resources :clients do
        collection { post :sort }
        resources :projects
      end
      resources :inquiries
      resources :posts do
        collection { post :sort }
      end
      match '/auth/:provider/callback' => 'omniauth#callback'
      match '/auth/failure' => 'omniauth#failure'
      resources :connections, only: [:index, :create, :destroy]
      resource :user
      root to: "posts#index"
    end
  end

  devise_for :user,     skip: :registrations
  resource   :user,     only: :show,           path: "/about"
  resources  :clients,  only: :index,          path: "/work"
  resources  :posts,    only: [:index, :show], path: "/blog/posts"
  resources  :services, only: [:index, :show]

  # Dynamic Root Route
  root to: "users#show"
  
end

app/helpers/layout_helper.rb
module LayoutHelper
  
  # Nested Layouts Helper  
  def parent_layout(layout)
    render :template => "layouts/#{layout}"
  end
  
  
  # Set title
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end

    
end

app/views/layouts/admin/application.html.haml
- content_for :content do
	#container
		= link_to "logout", destroy_user_session_url(subdomain: false), method: :delete, id: 'logout_link'
		%section#masthead.clearfix
			%header.clearfix
				%h1= resource_class
				%nav.horizontal
					%ul
						- unless current_page?(posts_path)	
							%li= link_to "blog", posts_path
						- unless current_page?(user_path)	
							%li= link_to "about", user_path
						- unless current_page?(clients_path)	
							%li= link_to "portfolio", clients_path
						- unless current_page?(services_path)	
							%li= link_to "services", services_path
	
		= content_for?(:body) ? yield(:body) : yield
	
= parent_layout 'boilerplate'