config/routes.rb
Briandmcnabb::Application.routes.draw do

  # Backend Administrative Interface
  constraints subdomain: "admin" do
    scope module: "admin", as: "admin"  do
      resources :services do
        collection { post :sort }
        resources :skills
      end
      resources :clients do
        collection { post :sort }
        resources :projects
      end
      resources :inquiries
      resources :posts do
        collection { post :sort }
      end
      match '/auth/:provider/callback' => 'omniauth#callback'
      match '/auth/failure' => 'omniauth#failure'
      resources :connections, only: [:index, :create, :destroy]
      resource :user
      root to: "posts#index"
    end
  end

  devise_for :user,     skip: :registrations
  resource   :user,     only: :show,           path: "/about"
  resources  :clients,  only: :index,          path: "/work"
  resources  :posts,    only: [:index, :show], path: "/blog/posts"
  resources  :services, only: [:index, :show]

  # Dynamic Root Route
  root to: "users#show"
  
end

app/models/connection.rb
class Connection < ActiveRecord::Base
  # Accessors
  attr_accessible :provider, :url

  # Associations
  belongs_to :user
  
  # Validations
  validates :provider, presence: true
  validates :username, presence: true
  validates :url,      presence: true
  
  # Callbacks
  before_validation(:on => :create) do
    self.username ||= self.url.split('/').last
  end
  
  
  # Methods
  
  class << self
    def find_with_omniauth(omniauth)
      where(provider: omniauth.provider, uid: omniauth.uid.to_s).first
    end
    
    def create_with_omniauth(auth_hash)
      create do |c|
        c.provider = auth_hash.provider
        c.uid      = auth_hash.uid.to_s
        c.url      = auth_hash.info.urls.select { |k,v| v if v && v.include?(auth_hash.provider) }.values[0]
        c.username = auth_hash.info.nickname
      end
    end
  end
  
end

app/controllers/admin/connections_controller.rb
class Admin::ConnectionsController < Admin::ResourceController
  actions :index, :create, :destroy
  
  def index
    @connections = current_user.connections.all
    @providers = %w(twitter github linkedin) - @connections.collect { |connection| connection.provider  }
    index!
  end
  
  
  protected
  
  def begin_of_association_chain
    current_user
  end
  
end

app/views/admin/connections/_connection.html.haml
.clearfix.connected[connection]
  = image_tag "#{connection.provider}.png", :size => "48x48", :alt => "#{connection.provider}"
  %p= connection.username
  = link_to "remove connection", admin_connection_path(connection), method: :delete, confirm: 'Are you sure you want to remove this connection?', class: "remove ir"

app/views/admin/connections/_form.html.haml
= simple_form_for [:admin, Connection.new] do |f|
  = link_to "Add Custom Connection", '#', id: 'unhide_form'
  %fieldset.hidden
    = f.input :provider, label: false, placeholder: "provider"
    = f.input :url, label: false, placeholder: "profile url"
    = f.button :submit, "submit"

app/views/admin/connections/index.html.haml
#connections
  = render collection
  
  - @providers.each do |provider|
    = link_to "/auth/#{provider}", class: "clearfix unconnected connection" do
      = image_tag "#{provider}.png", :size => "48x48", :alt => "#{provider}"
      %p= "connect to #{provider}"
  
  = render 'form'