config/routes.rb
Briandmcnabb::Application.routes.draw do

  # Backend Administrative Interface
  constraints subdomain: "admin" do
    scope module: "admin", as: "admin"  do
      resources :services do
        collection { post :sort }
        resources :skills
      end
      resources :clients do
        collection { post :sort }
        resources :projects
      end
      resources :inquiries
      resources :posts do
        collection { post :sort }
      end
      match '/auth/:provider/callback' => 'omniauth#callback'
      match '/auth/failure' => 'omniauth#failure'
      resources :connections, only: [:index, :create, :destroy]
      resource :user
      root to: "posts#index"
    end
  end

  devise_for :user,     skip: :registrations
  resource   :user,     only: :show,           path: "/about"
  resources  :clients,  only: :index,          path: "/work"
  resources  :posts,    only: [:index, :show], path: "/blog/posts"
  resources  :services, only: [:index, :show]

  # Dynamic Root Route
  root to: "users#show"
  
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id           :integer         not null, primary key
#  title        :string(255)
#  sub_title    :string(255)
#  body         :text
#  published_at :datetime
#  user_id      :integer
#  created_at   :datetime
#  updated_at   :datetime
#

class Post < ActiveRecord::Base

  # Accessors
  attr_accessible :title, :sub_title, :body, :publish
  def publish
    published_at.try(:strftime, "%b %-d, %Y")
  end

  def publish=(date)
    date  = date.split(/[\A,\s\z\s]/)
    date.delete("")
    year  = date[2]
    month = date[0]
    day   = date[1]
    self.published_at = Time.utc(year, month, day)
  end


  # Associations
  belongs_to :user
  

  # Scopes
  scope :published, lambda { where("published_at < ?", Time.now.to_date ) }
  
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::ResourceController
  protected
  def begin_of_association_chain 
    current_user 
  end
end

app/controllers/posts_controller.rb
class PostsController < ResourceController
  respond_to :atom
  
  protected
  def collection
    @posts ||= end_of_association_chain.published
  end
end

app/views/posts/_post.html.haml
- present post do |present_post|	
	%article.clearfix[post]
		.column_right
			%header
				%h1= present_post.title
				%h2= present_post.sub_title
			= present_post.body
			= disqus(post) unless current_page?(posts_path)
		%footer
			= present_post.published_at
			- if current_page?(posts_path)
				= present_post.comment_count
			- else
				#social_buttons
					#twitter= share_on_twitter post_url(post), "briandmcnabb", "#{post.title}: #{post.sub_title}"
					#google= google_plus_one post_url(post)
					#facebook= like_on_facebook post_url(post)	

app/views/posts/index.html.haml
- title "Blog"
- content_for :head do
	= auto_discovery_link_tag(:atom, posts_url(:atom))

%section#posts.clearfix
	= render collection

= enable_comment_count

app/views/posts/show.html.haml
- title "Blog"
-# title "#{resource.title}: #{resource.sub_title}"

= render resource